// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAim4NXvQG4V4lOr66TQNHriZ7kI2bqcDg',
    appId: '1:539345243502:web:7fc463e53668abb8af457f',
    messagingSenderId: '539345243502',
    projectId: 'chatapp-5fb30',
    authDomain: 'chatapp-5fb30.firebaseapp.com',
    storageBucket: 'chatapp-5fb30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApHCjPqO-D1wxmY_0vdqO2oHe3NIsJIw',
    appId: '1:539345243502:android:e22454b0bd249f6aaf457f',
    messagingSenderId: '539345243502',
    projectId: 'chatapp-5fb30',
    storageBucket: 'chatapp-5fb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38ks6XjJepcBER44qdjEjy0hXs5hrmLE',
    appId: '1:539345243502:ios:9b8deb1374db1441af457f',
    messagingSenderId: '539345243502',
    projectId: 'chatapp-5fb30',
    storageBucket: 'chatapp-5fb30.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38ks6XjJepcBER44qdjEjy0hXs5hrmLE',
    appId: '1:539345243502:ios:9b8deb1374db1441af457f',
    messagingSenderId: '539345243502',
    projectId: 'chatapp-5fb30',
    storageBucket: 'chatapp-5fb30.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAim4NXvQG4V4lOr66TQNHriZ7kI2bqcDg',
    appId: '1:539345243502:web:22878cb1027422a1af457f',
    messagingSenderId: '539345243502',
    projectId: 'chatapp-5fb30',
    authDomain: 'chatapp-5fb30.firebaseapp.com',
    storageBucket: 'chatapp-5fb30.firebasestorage.app',
  );
}
